title = "Victimes des pesticides du Québec"
baseURL = "https://hardcore-yalow-5dab64.netlify.com/"
tags = ["portfolio", "web design", "blog"]
languageCode = "fr-CA"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "tomanistor"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
  tagline = "Pour un Québec en santé sans pesticides"
  author = "Victimes des pesticides du Québec"
  description = ""
  logoBig = "VPQ_logo_Bicolore_RVB.png"
  logoSmall = "VPQ_logoINITIALES_Bicolore_RVB.png"
  favicon = "favicon.ico"
  opengraphImage = "/static/VPQ_logoINITIALES_Bicolore_RVB.png"
  email = ""
  googleTagManager = ""
  customCSS = true

  # Social media links in footer
  twitter = ""
  linkedin = ""
  github = ""
  facebook = ""

  # Membres organisationnels
  parkinsonQuebec = "https://parkinsonquebec.ca"
  autismeMtl = "http://autisme-montreal.com"

  # Copyright and theme author credit in footer
  copyright = true
  credit = false

  # Cache busting of static resources (additional set up required)
  cacheBustCSS = true
  cacheBustJS = true

  # Code highlighting with highlight.js
  highlightJS = true
  highlightJSStyle = "" # For custom highlight.js styles, add your /path/to/styles/default.css
  highlightJSScript = "" # For custom highlight.js languages config, add your /path/to/highlight.pack.js

  # Choose either Formspree contact form or Basin contact form
  ajaxFormspree = false
  ajaxFormspreeGold = false
  ajaxBasin = "https://usebasin.com/f/2c3ef5b1fb46"
  # Lazy loading with lazysizes
  lazyloading = true

[[menu.main]]
  name = "À Propos"
  url  = "/#about"
  weight = 1
[[menu.main]]
  name = "Mission"
  url  = "/#mission"
  weight = 2
[[menu.main]]
  name = "Actualités"
  url = "/#actualites"
  weight = 3
[[menu.main]]
  name = "Contact"
  url  = "/#contact"
  weight = 4
